version: "3.3"
services:
  app:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "8000:8000"
    image: fastapi-app
    volumes:
      - .:/src
    depends_on:
       - prometheus

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    environment:
      COMPOSE_HTTP_TIMEOUT: 60
    volumes:
      - ./prometheus.yml:/usr/local/bin/prometheus.yml/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    environment:
      COMPOSE_HTTP_TIMEOUT: 60
    depends_on:
      - prometheus